"""
api.py - FastAPI REST Web Service
----------------------------------
This script exposes the Epilepsy RAG system as a standard REST API:
- GET  /health : Checks that Qdrant, Hugging Face key, and Groq key are ready.
- POST /ask    : Accepts a question in JSON, runs the RAG pipeline, and returns
                 the grounded answer along with source chunk metadata.
- GET  /docs   : Auto-generated interactive Swagger UI documentation.
"""

from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from qdrant_client import QdrantClient

from main import get_env_value
from rag_chat import GROQ_MODEL, generate_rag_answer
from vector_store import COLLECTION_NAME, QDRANT_PATH


# -----------------------------------------------------------------------------
# FastAPI App Initialization
# -----------------------------------------------------------------------------
app = FastAPI(
    title="Epilepsy Clinical RAG API",
    description="REST API service for retrieving evidence and generating grounded answers from the clinical epilepsy knowledge base.",
    version="1.0.0",
)


# -----------------------------------------------------------------------------
# Request & Response Data Models (Pydantic)
# -----------------------------------------------------------------------------
class AskRequest(BaseModel):
    """Input payload accepted by the /ask question-answering endpoint."""

    question: str = Field(
        min_length=1,
        max_length=2_000,
        description="The clinical question or search query.",
        example="What are the main causes of epilepsy?",
    )
    limit: int = Field(
        default=4,
        ge=1,
        le=8,
        description="Number of context chunks to retrieve from Qdrant (1 to 8).",
    )


class Source(BaseModel):
    """A document chunk used as context for the generated answer."""

    id: int = Field(description="Unique chunk ID (0 to 411).")
    score: float = Field(description="Cosine similarity score.")
    metadata: dict[str, Any] = Field(description="Section and chapter hierarchy metadata.")


class AskResponse(BaseModel):
    """Output payload returned by the /ask endpoint."""

    answer: str = Field(description="The grounded medical answer generated by the LLM.")
    model: str = Field(description="LLM model identifier used for generation.")
    sources: list[Source] = Field(description="List of retrieved context passages.")


class HealthResponse(BaseModel):
    """Status payload indicating local service and API key availability."""

    ready: bool = Field(description="True if all dependencies are operational.")
    vector_database_ready: bool = Field(description="True if local Qdrant collection is accessible.")
    hugging_face_key_available: bool = Field(description="True if HF_TOKEN is configured.")
    groq_key_available: bool = Field(description="True if GROQ_API_KEY is configured.")


# -----------------------------------------------------------------------------
# Health Check Helper
# -----------------------------------------------------------------------------
def vector_database_is_ready() -> bool:
    """Confirm that the local Qdrant collection exists and can be opened."""
    if not QDRANT_PATH.is_dir():
        return False

    client = QdrantClient(path=str(QDRANT_PATH))
    try:
        return client.collection_exists(COLLECTION_NAME)
    finally:
        client.close()


# -----------------------------------------------------------------------------
# REST Endpoints
# -----------------------------------------------------------------------------
@app.get("/health", response_model=HealthResponse, tags=["Diagnostics"])
def health_check() -> HealthResponse:
    """Report the operational status of the RAG pipeline without exposing any secret keys."""
    database_ready = vector_database_is_ready()
    hf_key_available = bool(get_env_value("HF_TOKEN"))
    groq_key_available = bool(get_env_value("GROQ_API_KEY"))

    return HealthResponse(
        ready=database_ready and hf_key_available and groq_key_available,
        vector_database_ready=database_ready,
        hugging_face_key_available=hf_key_available,
        groq_key_available=groq_key_available,
    )


@app.post("/ask", response_model=AskResponse, tags=["RAG Inference"])
def ask_question(request: AskRequest) -> AskResponse:
    """Retrieve relevant chunks from Qdrant and generate a grounded, cited answer via Groq."""
    try:
        result = generate_rag_answer(request.question, request.limit)
    except (ValueError, FileNotFoundError) as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
    except RuntimeError as error:
        raise HTTPException(status_code=502, detail=str(error)) from error

    # Return safe structured source models (internal prompt representations excluded)
    sources = [
        Source(id=item["id"], score=item["score"], metadata=item["metadata"])
        for item in result["sources"]
    ]
    return AskResponse(answer=result["answer"], model=GROQ_MODEL, sources=sources)

